Analytics Spec
mlabs-haskell/hydra-auction-frontend pull request #11
Opened 2024-05-01 23:46 UTC by SamDelaney

2024-05-06 16:06 UTC, euonymos commented on docs/analytics_spec.md
> +  unitId: unit,
Is that `unitId` sort of event identifier?

2024-05-06 16:07 UTC, euonymos commented on docs/analytics_spec.md
> +Triggers when the `announceAuction` transaction succeeds.
Do we have an auction identifier here somewhere?

2024-05-06 16:13 UTC, euonymos requested changes
LGTM @SamDelaney, dropped a couple of question.

I think we have enough events to begin with, probably it's time to start moving from the other end, I mean reports and embedded widgets we are going to implement. From what comes to my mind:
* Delegate group performance (# auctions completed, # of auctions aborted)
* Seller statistics (#auctions completed)
* Bidder statistics (# bids, # wins, #failures to purchase)
* Lot summary (# of auctions, lowest and highest prices?)

2024-06-07 01:16 UTC, SamDelaney commented
@euonymos addressed your comments. Further development of the spec will require events & a demo project for testing, so I plan on closing this PR and revisiting later, barring further feedback.

2024-06-25 17:46 UTC, merged